name: Automated tests run

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Run API Tests
        run: mvn clean verify -Denvironment=dev
        env:
          API_USER: ${{ secrets.API_USER }}
          API_PASS: ${{ secrets.API_PASS }}